version: '3.8'

services:
  # Frontend React para desenvolvimento
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: investpro-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_I18N_API_URL=http://localhost:3000
      - VITE_ACCOUNT_API_URL=http://localhost:4000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    name: investpro-frontend-network
